// This file is automatically generated. Do not edit it directly.
// Re-export the safe client from lib/supabase so there is only ONE instance
// and it automatically no-ops when no API key is configured.
export { supabase } from "../../lib/supabase";