// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list_surahs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/data/surahs.ts
var surahs = [
  { number: 1, name: "\u0627\u0644\u0641\u0627\u062A\u062D\u0629", ayahCount: 7 },
  { number: 2, name: "\u0627\u0644\u0628\u0642\u0631\u0629", ayahCount: 286 },
  { number: 3, name: "\u0622\u0644 \u0639\u0645\u0631\u0627\u0646", ayahCount: 200 },
  { number: 4, name: "\u0627\u0644\u0646\u0633\u0627\u0621", ayahCount: 176 },
  { number: 5, name: "\u0627\u0644\u0645\u0627\u0626\u062F\u0629", ayahCount: 120 },
  { number: 6, name: "\u0627\u0644\u0623\u0646\u0639\u0627\u0645", ayahCount: 165 },
  { number: 7, name: "\u0627\u0644\u0623\u0639\u0631\u0627\u0641", ayahCount: 206 },
  { number: 8, name: "\u0627\u0644\u0623\u0646\u0641\u0627\u0644", ayahCount: 75 },
  { number: 9, name: "\u0627\u0644\u062A\u0648\u0628\u0629", ayahCount: 129 },
  { number: 10, name: "\u064A\u0648\u0646\u0633", ayahCount: 109 },
  { number: 11, name: "\u0647\u0648\u062F", ayahCount: 123 },
  { number: 12, name: "\u064A\u0648\u0633\u0641", ayahCount: 111 },
  { number: 13, name: "\u0627\u0644\u0631\u0639\u062F", ayahCount: 43 },
  { number: 14, name: "\u0625\u0628\u0631\u0627\u0647\u064A\u0645", ayahCount: 52 },
  { number: 15, name: "\u0627\u0644\u062D\u062C\u0631", ayahCount: 99 },
  { number: 16, name: "\u0627\u0644\u0646\u062D\u0644", ayahCount: 128 },
  { number: 17, name: "\u0627\u0644\u0625\u0633\u0631\u0627\u0621", ayahCount: 111 },
  { number: 18, name: "\u0627\u0644\u0643\u0647\u0641", ayahCount: 110 },
  { number: 19, name: "\u0645\u0631\u064A\u0645", ayahCount: 98 },
  { number: 20, name: "\u0637\u0647", ayahCount: 135 },
  { number: 21, name: "\u0627\u0644\u0623\u0646\u0628\u064A\u0627\u0621", ayahCount: 112 },
  { number: 22, name: "\u0627\u0644\u062D\u062C", ayahCount: 78 },
  { number: 23, name: "\u0627\u0644\u0645\u0624\u0645\u0646\u0648\u0646", ayahCount: 118 },
  { number: 24, name: "\u0627\u0644\u0646\u0648\u0631", ayahCount: 64 },
  { number: 25, name: "\u0627\u0644\u0641\u0631\u0642\u0627\u0646", ayahCount: 77 },
  { number: 26, name: "\u0627\u0644\u0634\u0639\u0631\u0627\u0621", ayahCount: 227 },
  { number: 27, name: "\u0627\u0644\u0646\u0645\u0644", ayahCount: 93 },
  { number: 28, name: "\u0627\u0644\u0642\u0635\u0635", ayahCount: 88 },
  { number: 29, name: "\u0627\u0644\u0639\u0646\u0643\u0628\u0648\u062A", ayahCount: 69 },
  { number: 30, name: "\u0627\u0644\u0631\u0648\u0645", ayahCount: 60 },
  { number: 31, name: "\u0644\u0642\u0645\u0627\u0646", ayahCount: 34 },
  { number: 32, name: "\u0627\u0644\u0633\u062C\u062F\u0629", ayahCount: 30 },
  { number: 33, name: "\u0627\u0644\u0623\u062D\u0632\u0627\u0628", ayahCount: 73 },
  { number: 34, name: "\u0633\u0628\u0623", ayahCount: 54 },
  { number: 35, name: "\u0641\u0627\u0637\u0631", ayahCount: 45 },
  { number: 36, name: "\u064A\u0633", ayahCount: 83 },
  { number: 37, name: "\u0627\u0644\u0635\u0627\u0641\u0627\u062A", ayahCount: 182 },
  { number: 38, name: "\u0635", ayahCount: 88 },
  { number: 39, name: "\u0627\u0644\u0632\u0645\u0631", ayahCount: 75 },
  { number: 40, name: "\u063A\u0627\u0641\u0631", ayahCount: 85 },
  { number: 41, name: "\u0641\u0635\u0644\u062A", ayahCount: 54 },
  { number: 42, name: "\u0627\u0644\u0634\u0648\u0631\u0649", ayahCount: 53 },
  { number: 43, name: "\u0627\u0644\u0632\u062E\u0631\u0641", ayahCount: 89 },
  { number: 44, name: "\u0627\u0644\u062F\u062E\u0627\u0646", ayahCount: 59 },
  { number: 45, name: "\u0627\u0644\u062C\u0627\u062B\u064A\u0629", ayahCount: 37 },
  { number: 46, name: "\u0627\u0644\u0623\u062D\u0642\u0627\u0641", ayahCount: 35 },
  { number: 47, name: "\u0645\u062D\u0645\u062F", ayahCount: 38 },
  { number: 48, name: "\u0627\u0644\u0641\u062A\u062D", ayahCount: 29 },
  { number: 49, name: "\u0627\u0644\u062D\u062C\u0631\u0627\u062A", ayahCount: 18 },
  { number: 50, name: "\u0642", ayahCount: 45 },
  { number: 51, name: "\u0627\u0644\u0630\u0627\u0631\u064A\u0627\u062A", ayahCount: 60 },
  { number: 52, name: "\u0627\u0644\u0637\u0648\u0631", ayahCount: 49 },
  { number: 53, name: "\u0627\u0644\u0646\u062C\u0645", ayahCount: 62 },
  { number: 54, name: "\u0627\u0644\u0642\u0645\u0631", ayahCount: 55 },
  { number: 55, name: "\u0627\u0644\u0631\u062D\u0645\u0646", ayahCount: 78 },
  { number: 56, name: "\u0627\u0644\u0648\u0627\u0642\u0639\u0629", ayahCount: 96 },
  { number: 57, name: "\u0627\u0644\u062D\u062F\u064A\u062F", ayahCount: 29 },
  { number: 58, name: "\u0627\u0644\u0645\u062C\u0627\u062F\u0644\u0629", ayahCount: 22 },
  { number: 59, name: "\u0627\u0644\u062D\u0634\u0631", ayahCount: 24 },
  { number: 60, name: "\u0627\u0644\u0645\u0645\u062A\u062D\u0646\u0629", ayahCount: 13 },
  { number: 61, name: "\u0627\u0644\u0635\u0641", ayahCount: 14 },
  { number: 62, name: "\u0627\u0644\u062C\u0645\u0639\u0629", ayahCount: 11 },
  { number: 63, name: "\u0627\u0644\u0645\u0646\u0627\u0641\u0642\u0648\u0646", ayahCount: 11 },
  { number: 64, name: "\u0627\u0644\u062A\u063A\u0627\u0628\u0646", ayahCount: 18 },
  { number: 65, name: "\u0627\u0644\u0637\u0644\u0627\u0642", ayahCount: 12 },
  { number: 66, name: "\u0627\u0644\u062A\u062D\u0631\u064A\u0645", ayahCount: 12 },
  { number: 67, name: "\u0627\u0644\u0645\u0644\u0643", ayahCount: 30 },
  { number: 68, name: "\u0627\u0644\u0642\u0644\u0645", ayahCount: 52 },
  { number: 69, name: "\u0627\u0644\u062D\u0627\u0642\u0629", ayahCount: 52 },
  { number: 70, name: "\u0627\u0644\u0645\u0639\u0627\u0631\u062C", ayahCount: 44 },
  { number: 71, name: "\u0646\u0648\u062D", ayahCount: 28 },
  { number: 72, name: "\u0627\u0644\u062C\u0646", ayahCount: 28 },
  { number: 73, name: "\u0627\u0644\u0645\u0632\u0645\u0644", ayahCount: 20 },
  { number: 74, name: "\u0627\u0644\u0645\u062F\u062B\u0631", ayahCount: 56 },
  { number: 75, name: "\u0627\u0644\u0642\u064A\u0627\u0645\u0629", ayahCount: 40 },
  { number: 76, name: "\u0627\u0644\u0625\u0646\u0633\u0627\u0646", ayahCount: 31 },
  { number: 77, name: "\u0627\u0644\u0645\u0631\u0633\u0644\u0627\u062A", ayahCount: 50 },
  { number: 78, name: "\u0627\u0644\u0646\u0628\u0623", ayahCount: 40 },
  { number: 79, name: "\u0627\u0644\u0646\u0627\u0632\u0639\u0627\u062A", ayahCount: 46 },
  { number: 80, name: "\u0639\u0628\u0633", ayahCount: 42 },
  { number: 81, name: "\u0627\u0644\u062A\u0643\u0648\u064A\u0631", ayahCount: 29 },
  { number: 82, name: "\u0627\u0644\u0627\u0646\u0641\u0637\u0627\u0631", ayahCount: 19 },
  { number: 83, name: "\u0627\u0644\u0645\u0637\u0641\u0641\u064A\u0646", ayahCount: 36 },
  { number: 84, name: "\u0627\u0644\u0627\u0646\u0634\u0642\u0627\u0642", ayahCount: 25 },
  { number: 85, name: "\u0627\u0644\u0628\u0631\u0648\u062C", ayahCount: 22 },
  { number: 86, name: "\u0627\u0644\u0637\u0627\u0631\u0642", ayahCount: 17 },
  { number: 87, name: "\u0627\u0644\u0623\u0639\u0644\u0649", ayahCount: 19 },
  { number: 88, name: "\u0627\u0644\u063A\u0627\u0634\u064A\u0629", ayahCount: 26 },
  { number: 89, name: "\u0627\u0644\u0641\u062C\u0631", ayahCount: 30 },
  { number: 90, name: "\u0627\u0644\u0628\u0644\u062F", ayahCount: 20 },
  { number: 91, name: "\u0627\u0644\u0634\u0645\u0633", ayahCount: 15 },
  { number: 92, name: "\u0627\u0644\u0644\u064A\u0644", ayahCount: 21 },
  { number: 93, name: "\u0627\u0644\u0636\u062D\u0649", ayahCount: 11 },
  { number: 94, name: "\u0627\u0644\u0634\u0631\u062D", ayahCount: 8 },
  { number: 95, name: "\u0627\u0644\u062A\u064A\u0646", ayahCount: 8 },
  { number: 96, name: "\u0627\u0644\u0639\u0644\u0642", ayahCount: 19 },
  { number: 97, name: "\u0627\u0644\u0642\u062F\u0631", ayahCount: 5 },
  { number: 98, name: "\u0627\u0644\u0628\u064A\u0646\u0629", ayahCount: 8 },
  { number: 99, name: "\u0627\u0644\u0632\u0644\u0632\u0644\u0629", ayahCount: 8 },
  { number: 100, name: "\u0627\u0644\u0639\u0627\u062F\u064A\u0627\u062A", ayahCount: 11 },
  { number: 101, name: "\u0627\u0644\u0642\u0627\u0631\u0639\u0629", ayahCount: 11 },
  { number: 102, name: "\u0627\u0644\u062A\u0643\u0627\u062B\u0631", ayahCount: 8 },
  { number: 103, name: "\u0627\u0644\u0639\u0635\u0631", ayahCount: 3 },
  { number: 104, name: "\u0627\u0644\u0647\u0645\u0632\u0629", ayahCount: 9 },
  { number: 105, name: "\u0627\u0644\u0641\u064A\u0644", ayahCount: 5 },
  { number: 106, name: "\u0642\u0631\u064A\u0634", ayahCount: 4 },
  { number: 107, name: "\u0627\u0644\u0645\u0627\u0639\u0648\u0646", ayahCount: 7 },
  { number: 108, name: "\u0627\u0644\u0643\u0648\u062B\u0631", ayahCount: 3 },
  { number: 109, name: "\u0627\u0644\u0643\u0627\u0641\u0631\u0648\u0646", ayahCount: 6 },
  { number: 110, name: "\u0627\u0644\u0646\u0635\u0631", ayahCount: 3 },
  { number: 111, name: "\u0627\u0644\u0645\u0633\u062F", ayahCount: 5 },
  { number: 112, name: "\u0627\u0644\u0625\u062E\u0644\u0627\u0635", ayahCount: 4 },
  { number: 113, name: "\u0627\u0644\u0641\u0644\u0642", ayahCount: 5 },
  { number: 114, name: "\u0627\u0644\u0646\u0627\u0633", ayahCount: 6 }
];

// src/lib/mcp/tools/list_surahs.ts
var list_surahs_default = defineTool({
  name: "list_surahs",
  title: "List Quran surahs",
  description: "List all 114 surahs of the Quran with their number, Arabic name, and ayah count.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(surahs) }],
    structuredContent: { surahs }
  })
});

// src/lib/mcp/tools/get_surah.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var get_surah_default = defineTool2({
  name: "get_surah",
  title: "Get surah info",
  description: "Get information about a specific surah by its number (1-114).",
  inputSchema: {
    number: z.number().int().min(1).max(114).describe("Surah number, 1 through 114.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ number }) => {
    const surah = surahs.find((s) => s.number === number);
    if (!surah) {
      return { content: [{ type: "text", text: `No surah with number ${number}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(surah) }],
      structuredContent: { surah }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool3({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id and email for the current MCP session.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = { user_id: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gimdekpxutvnopovofmc";
var mcp_default = defineMcp({
  name: "learn-quran-kids-mcp",
  title: "\u0627\u0644\u0645\u0635\u062D\u0641 \u0627\u0644\u0645\u0639\u0644\u0645 \u0628\u0631\u0648\u0627\u064A\u0629 \u0648\u0631\u0634 \u2014 MCP",
  version: "0.1.0",
  instructions: "Tools for the Learn Quran Kids app (Warsh narration by Amin Haj Ayoub). Use `list_surahs` to list all 114 surahs, `get_surah` to look up one by number, and `whoami` to confirm the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_surahs_default, get_surah_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
